### ISSUE TITLE
504 errors on upload

### ISSUE THREAD

**Issue by meetar** [polygon-city/building-database-obj-importer#2]
Crashing due to unhandled exception on the occasional empty JSON object:

```
/building-database-obj-importer/index.js:268
      throw e;
            ^
SyntaxError: Unexpected end of input
    at Object.parse (native)
    at Request._callback (/building-database-obj-importer/index.js:265:32)
    at Request.self.callback (/building-database-obj-importer/node_modules/request/request.js:198:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/building-database-obj-importer/node_modules/request/request.js:1073:14)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (/building-database-obj-importer/node_modules/request/request.js:1019:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
```

I found that in these cases the `model` variable is undefined, so https://github.com/polygon-city/building-database-obj-importer/blob/master/index.js#L233 is failing somehow – the files it's failing on are all very small (the largest so far is 5k) but apparently well-formed, so I assume it's some kind of race condition.

If I just wrap the JSON.parse like so

```
try {
  var savedBuilding = JSON.parse(body);
} catch (e) {
  console.log('error parsing JSON:\n', body);
  done();
  return;
}
```

I get a lot of empty `body` responses, but the upload continues successfully.

**Comment by robhawkes** [comment]
I'm trying to work out a way to replicate this so I can dig into it – so far I'm unable to see any `undefined` `formData.model` values when running over the entire Mitte dataset (without actually uploading, which may be a key part of the problem).

In fact, if I manually set `formData.model` to `undefined` then the request package I'm using will crash out before it sends anything to the server. This suggests that we'd be seeing a crash much earlier if the model data really wasn't being sent to the server.

What's most interesting is that there's nothing in the response body. The server should at least return a JSON object with an error if something goes wrong, otherwise a JSON success object with a building message. The fact that it's empty is surprising as there's nothing in the code that could return an empty response.

I've pushed de65356 which adds some debugging for the response HTTP code and headers, plus adding in a `try…catch` for the bad JSON. This won't fix it but it may give us a better idea on what it going wrong should it happen again (eg. it could be a HTTP timeout or a temporary server hiccup).

Some questions (as I'm unable to replicate yet):
- Do the models that fail here still get uploaded ok?
- Do you have the ID of some of the offending models so I can see if there's anything weird about them?
- Does it happen to the same models each time?
- By occasional, how often are we talking?
- Can you upload the crashing models manually to Polygon City via the `…/add` endpoint?

**Comment by meetar** [comment]
Nothing special about the models – and it's not always the same models each time. Restarting a batch will send failed models through successfully, though it might take a couple of tries. However, it's frequently the same models, especially the ones at the top of the list, around the 6-12 positions. Even if I set the queue size to 1, the script fires off about half a dozen requests at once, and most come back fine, but the next few in a row typically fail with 504s.

Occasionally something causes the uploads to hang, and then all subsequent uploads will be returned as 504s.

I think all we need here is for upload failures to be handled, and the file in question to be added back to the queue.

**Comment by robhawkes** [comment]
Ok, I've pushed an update to Polygon City that better handles errors when retrieving location data from a remote source (which was causing the 504s). What this does now is pass on the HTTP error reported by the location API (in this case, Pelias) and so all those 504s we were seeing are actually because of 429 Too Many Requests responses (or other non-200 responses) from the location API – we're being rate-limited.

Do you know what the rate-limit is for Pelias so I can implement a queue that ensures we don't go over it? That _should_ fix our current upload failures.

**Comment by meetar** [comment]
Rate-limits now accounted for, issue resolved

**Comment by robhawkes** [comment]
Fingers crossed that it stays that way! 😅
