### ISSUE TITLE
Failed to update building location: HTTP 429

### ISSUE THREAD

**Issue by meetar** [polygon-city/building-database-obj-importer#4]
After every building upload, a 429 (Too Many Requests) is logged:

```
Skipping error: Failed to update building location: HTTP 429
```

However, the buildings appear to be added and placed correctly.

**Comment by robhawkes** [comment]
The 429 errors are related to the uploads causing Pelias to rate-limit things (see #2), which I'll add in a fix for shortly.

The building shouldn't get added though if this happens, as it exits the upload process before being added to the database. We can confirm this because the JSON response we get has an error property, otherwise we wouldn't see the error output. In any case, it definitely shouldn't have a location attached as that data is missing when we get the 429 response from Pelias, so there's no where it could be coming from.

How are you confirming that the building was added and placed correctly? Could it be a duplicate from a previous, successful upload attempt?

**Comment by meetar** [comment]
I'd cleared out the db previously, but apparently there were some getting through. This problem has been solved by the rate-limit fixes!
